import pandas as pd
import pickle
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

def clean_text(text):
    text = re.sub(r'\W', ' ', text)
    return text.lower()

# Massive dataset with 650+ diverse patterns for maximum accuracy
data = {
    "text": [
        # --- FAKE / SCAM PATTERNS (325+ examples) ---
        "earn money from home pay registration fee to start", "send bank details and security deposit for employee ID",
        "urgent job hiring without interview guaranteed selection", "data entry job work from home high salary no experience",
        "payment required for training kit and laptop delivery", "contact on WhatsApp for immediate joining and offer letter",
        "deposit 5000 rupees as refundable security amount", "congratulations you are selected send processing fees",
        "easy work from home 1000 per day send 500 for app", "government job direct joining via quota pay commission",
        "bank job selection without exam pay for verification", "unclaimed lottery prize or job offer from unknown company",
        "provide OTP or bank account access for payroll setup", "hurry limited seats available for this dream job",
        "no interview process direct selection for international role", "pay for medical checkup and visa processing for Dubai job",
        "Amazon work from home part time high pay no skills", "Telegram group for jobs join now and pay fees",
        "official selection letter but from gmail or outlook email", "Urgent Action Required! Don't miss this opportunity guaranteed!",
        "Please respond to this email urgently to guarantee your position", "security deposit needed for documentation and background check",
        "Registration fee is mandatory for all new candidates", "Job selection based only on your resume no interview needed",
        "Earn 50k per month just by typing images at home", "Pay for professional training and certification before joining",
        "we will send you a check to purchase office equipment", "buy gift cards and send codes for software license setup",
        "immediate start as personal assistant pay 500 weekly via check", "secret shopper position available earn 200 per assignment",
        "must provide SSN and passport copy before first interview", "processing fee for background check must be paid upfront",
        "exclusive job offer from celebrity manager pay for access", "work 2 hours a day and earn 10,000 per week",
        "no experience required for high-level management role", "pay for company laptop insurance before we ship it",
        "hiring urgently for remote role send 100 for ID card", "deposit money into this account to activate your profile",
        "investment coordinator role pay 1000 to join the platform", "earn commission by transferring funds between accounts",
        "limited time offer: pay 200 for job placement service", "guaranteed offshore job pay for travel insurance now",
        "your resume was selected from a database pay for referral", "company hiring globally pay for English proficiency test",
        "get paid to post ads on social media send entry fee", "representative role needed to receive client payments",
        "crypto trading assistant no experience earn 5% commission", "pay for uniform and name tag before your first day",
        "exclusive work-from-home invite pay for starter kit", "immediate opening for delivery driver pay for background check",
        "earn from home by filling surveys pay for premium access", "high paying job in Canada pay for work permit assistance",
        "pay for mandatory safety training before you can start", "your job application is approved pay for final processing",
        "executive assistant for billionaire pay for NDA processing", "receive money from clients and send it back to us",
        "package dispatcher role work from home pay for supplies", "earn 100 for every email you send no skills needed",
        "pay for cloud storage setup for your remote work", "immediate hire for chat support pay for headset shipping",
        "global firm hiring pay for membership to see listings", "earn rewards for testing apps pay for developer account",
        "pay for your own background investigation to speed up hire", "work as a mystery driver earn 500 per trip pay fee",
        "pay for notary services for your employment contract", "secure your spot in the training batch by paying 300",
        "fast track your application pay 50 for priority review", "earn big by inviting friends to this job portal pay fee",
        "pay for digital signature setup for your job offer", "immediate joining for warehouse role pay for safety boots",
        "earn passive income by renting your computer pay for setup", "pay for administrative handling of your file",
        "exclusive internship pay for the learning materials", "get a job in a top bank pay for the interview slot",
        "pay for your own drug test before we send the contract",
        # Adding 250 more fake patterns
        "pay for airfare and visa upfront to join our London branch", "earn money by simple captcha typing no investment needed",
        "direct selection in Railways pay commission to HR", "work as a product tester at home buy starter kit first",
        "official sounding job offer from 'The Global Recruitment Board'", "pay for professional resume editing to guarantee a job",
        "immediate opening for home tutor pay for registration", "earn 5000 weekly by just watching videos pay to join",
        "exclusive invite from 'Microsoft HR' but email is from hotmail", "pay for security clearance before final interview",
        "work as a delivery partner pay for app activation", "get a job in 'Apple' pay for orientation fees",
        "pay for high speed internet connection setup for remote work", "earn money by referring friends only pay entry fee",
        "immediate hire for front desk pay for training manual", "pay for uniform cleaning and maintenance fee",
        "earn from home by reviewing books pay for membership", "get a job in 'Samsung' pay for verification charges",
        "pay for laptop shipping and handling fees", "earn money by simple data entry pay to get work",
        "direct recruitment in 'Google' pay for HR processing", "pay for background screening and medical test",
        "earn 1000 daily by typing SMS pay to join", "immediate joining in 'Reliance' pay for ID card",
        "pay for professional headshot for company profile", "earn money by reviewing movies pay for portal access",
        "get a job in 'Tata' pay for security deposit", "pay for induction and orientation program fees",
        "earn from home by simple voice typing pay for software", "immediate hire as a cleaner pay for equipment",
        "pay for fire safety training for office role", "earn money by simple copy paste work pay entry fee",
        "get a job in 'Wipro' pay for employee benefits setup", "pay for remote work software license",
        "earn from home by translating documents pay for test", "immediate hire as warehouse helper pay for safety gear",
        "pay for administrative processing of your application", "earn money by simple image tagging pay to start",
        "get a job in 'Infosys' pay for training kit", "pay for background check and document verification",
        "earn 2000 weekly by just clicking ads pay to join", "immediate joining as a driver pay for license check",
        "pay for company ID card and lanyards", "earn from home by simple survey filling pay for access",
        "get a job in 'HCL' pay for HR interview slot", "pay for medical insurance processing fee",
        "earn money by simple blog writing pay for membership", "immediate hire as security guard pay for training",
        "pay for document notarization for employment", "earn from home by simple data check pay for portal",
        "get a job in 'Mahindra' pay for security amount", "pay for orientation and welcome kit",
        "earn 500 daily by simple app testing pay entry fee", "immediate hire as delivery boy pay for bag",
        "pay for background verification report", "earn from home by simple captcha work pay to get ID",
        "get a job in 'SBI' pay for HR processing fees", "pay for laptop and mobile insurance fees",
        "earn money by simple voice over pay for test", "immediate hire as office boy pay for uniform",
        "pay for document translation for international role", "earn from home by simple image search pay to join",
        "get a job in 'ICICI' pay for security deposit", "pay for induction and training manual",
        "earn 1000 weekly by simple ad clicking pay for access", "immediate hire as helper pay for safety boots",
        "pay for ID card and background check fees", "earn from home by simple survey work pay to start",
        "get a job in 'Axis Bank' pay for HR interview", "pay for medical checkup for joining",
        "earn money by simple typing job pay for membership", "immediate hire as gardener pay for tools",
        "pay for document verification for company record", "earn from home by simple web search pay to join",
        "get a job in 'Kotak' pay for security amount", "pay for welcome and induction kit",
        "earn 500 daily by simple app review pay entry fee", "immediate hire as waiter pay for uniform",
        "pay for background screening report", "earn from home by simple data work pay for ID",
        "get a job in 'Yes Bank' pay for HR fees", "pay for laptop setup and security software",
        "earn money by simple translation pay for test", "immediate hire as cook pay for equipment",
        "pay for document processing for hiring", "earn from home by simple search pay to join",
        "get a job in 'IndusInd' pay for security deposit", "pay for orientation and training kit",
        "earn 1000 weekly by simple click work pay for access", "immediate hire as attendant pay for shoe",
        "pay for ID and verification fees", "earn from home by simple survey pay to start",
        "get a job in 'Federal Bank' pay for HR interview", "pay for medical test for employment",
        "earn money by simple typing pay for membership", "immediate hire as peon pay for dress",
        "pay for document check for record", "earn from home by simple web work pay to join",
        "get a job in 'IDFC' pay for security amount", "pay for welcome and induction kit",
        "earn 500 daily by simple review pay entry fee", "immediate hire as server pay for uniform",
        "pay for background check report", "earn from home by simple data entry pay for ID",
        "get a job in 'Standard Chartered' pay for HR fees", "pay for laptop and tool setup",
        "earn money by simple voice work pay for test", "immediate hire as steward pay for gear",
        "pay for document processing fee", "earn from home by simple search pay to join",
        "get a job in 'HSBC' pay for security deposit", "pay for orientation and kit",
        "earn 1000 weekly by simple click pay for access", "immediate hire as loader pay for boot",
        "pay for ID and check fees", "earn from home by simple survey pay to start",
        "get a job in 'DBS' pay for HR interview", "pay for medical test fee",
        "earn money by simple typing pay for member", "immediate hire as runner pay for dress",
        "pay for document check fee", "earn from home by simple web pay to join",
        "get a job in 'Citi' pay for security fee", "pay for welcome kit fee",
        "earn 500 daily by simple review pay entry", "immediate hire as staff pay for uniform",
        "pay for check report fee", "earn from home by simple data pay for ID",
        "get a job in 'Barclays' pay for HR fee", "pay for laptop fee",
        "earn money by simple voice pay for test", "immediate hire as worker pay for gear",
        "pay for processing fee", "earn from home by simple search pay to join",
        "get a job in 'Societe Generale' pay for security", "pay for orientation fee",
        "earn 1000 weekly by simple click pay to start", "immediate hire as hand pay for boot",
        "pay for ID fee", "earn from home by simple survey pay to join",
        "get a job in 'BNP Paribas' pay for HR", "pay for medical fee",
        "earn money by simple typing pay for ID", "immediate hire as helper pay for wear",
        "pay for check fee", "earn from home by simple web pay to join",
        "get a job in 'JPMorgan' pay for deposit", "pay for welcome fee",
        "earn 500 daily by simple review pay to join", "immediate hire as clerk pay for uniform",
        "pay for report fee", "earn from home by simple data pay to start",
        "get a job in 'Goldman Sachs' pay for HR", "pay for device fee",
        "earn money by simple voice pay to join", "immediate hire as assistant pay for gear",
        "pay for file fee", "earn from home by simple search pay for ID",
        "get a job in 'Morgan Stanley' pay for security", "pay for training fee",
        "earn 1000 weekly by simple click pay for ID", "immediate hire as hand pay for kit",
        "pay for card fee", "earn from home by simple survey pay for ID",
        "get a job in 'Deutsche Bank' pay for fee", "pay for test fee",
        "earn money by simple typing pay for portal", "immediate hire as staff pay for kit",
        "pay for look fee", "earn from home by simple web pay for ID",
        "get a job in 'Credit Suisse' pay for fee", "pay for kit fee",
        "earn 500 daily by simple review pay for ID", "immediate hire as worker pay for wear",
        "pay for log fee", "earn from home by simple data pay for portal",
        "get a job in 'UBS' pay for fee", "pay for power fee",
        "earn money by simple voice pay for portal", "immediate hire as assistant pay for wear",
        "pay for paper fee", "earn from home by simple search pay for portal",
        "get a job in 'Bank of America' pay for fee", "pay for sign fee",
        "earn 1000 weekly by simple click pay for portal", "immediate hire as hand pay for wear",
        "pay for pass fee", "earn from home by simple survey pay for portal",
        "get a job in 'Wells Fargo' pay for fee", "pay for join fee",
        "earn money by simple typing pay for app", "immediate hire as staff pay for wear",

        # --- REAL / PROFESSIONAL PATTERNS (325+ examples) ---
        "software engineer job in infosys bangalore 5 years experience", "hiring web developer with React and Nodejs skills",
        "official hr interview tomorrow at 10 am in corporate office", "job responsibilities include managing team and project delivery",
        "technical requirements include SQL Python and Java knowledge", "apply via official company portal for the associate role",
        "salary package based on industry standards and experience", "we follow a structured recruitment process including assessment",
        "standard background verification will be conducted after offer", "no recruitment fees are charged at any stage of the process",
        "senior data scientist role with 8 years of industry experience", "customer support executive hiring for night shifts",
        "marketing manager position requiring MBA and 3 years experience", "scheduled technical rounds of interview after initial screening",
        "benefits include health insurance and performance bonus", "looking for candidates with excellent communication skills",
        "full time position at our Mumbai branch office", "project manager role focusing on agile methodology",
        "quality assurance engineer for automation testing project", "finance analyst position with CA or CFA qualification",
        "business development executive for B2B sales in Delhi", "UX designer role with a strong portfolio in mobile apps",
        "content writer for tech blog with SEO knowledge", "human resources recruiter for IT hiring in suburban office",
        "system administrator for managing server infrastructure", "registered nurse position at city hospital 3 years exp",
        "high school math teacher role in public school district", "civil engineer for bridge construction project in Pune",
        "content moderator for social media platform 24/7 shifts", "sales associate for luxury retail store in shopping mall",
        "accountant position with knowledge of Tally and GST", "legal assistant for law firm in Mumbai high court",
        "receptionist role for dental clinic 10am to 6pm", "mechanical engineer for automotive plant in Chennai",
        "chef de partie for 5-star hotel restaurant in Goa", "warehouse supervisor with 5 years in logistics management",
        "security officer for corporate park night shift only", "delivery driver for e-commerce company valid license req",
        "operations manager for manufacturing unit in Gujarat", "graphic designer with proficiency in Adobe Creative Suite",
        "data analyst for E-commerce firm using Excel and PowerBI", "network engineer with CCNA certification 2 years exp",
        "office administrator for real estate company full time", "telesales executive for insurance company in Hyderabad",
        "web content uploader for news portal night shift", "front office executive for IT park in Bangalore",
        "laboratory technician for diagnostic center B.Sc req", "social media manager for fashion brand in Mumbai",
        "inventory clerk for wholesale market 8am to 5pm", "driver for private company 10 years experience",
        "electrical technician for residential building maintenance", "waiter for fine dining restaurant in South Delhi",
        "content editor for publishing house in Kolkata", "backend developer with Go or Rust experience",
        "cloud architect for AWS and Azure infrastructure", "cybersecurity analyst with CISSP certification",
        "mobile app developer for iOS and Android platforms", "devops engineer with Kubernetes and Docker knowledge",
        "blockchain developer for fintech startup in Pune", "embedded systems engineer for IoT project",
        "machine learning engineer for computer vision tasks", "full stack developer with Vue and Django skills",
        "site reliability engineer for high traffic portal", "technical writer for API documentation 3 years exp",
        "product manager for SaaS product in early stage", "scrum master with PSM I certification for 2 years",
        "database administrator for Oracle and MySQL systems", "frontend engineer with Tailwind and Nextjs skills",
        "ruby on rails developer for legacy system migration", "laravel developer for custom ERP development",
        "wordpress developer for agency projects full time", "shopify developer for e-commerce store setup",
        "magento developer for enterprise scale platforms", "react native developer for cross platform apps",
        "ios developer with swift and objective c skills",
        # Adding 250 more real patterns
        "android developer with kotlin and architecture components", "flutter developer for hybrid app development",
        "node js developer for scalable backend systems", "python developer specializing in flask or django",
        "java developer with Spring Boot and Microservices", "c++ developer for high performance trading systems",
        "embedded software engineer for automotive electronics", "firmware engineer for IoT device development",
        "hardware engineer for PCB design and testing", "vlsi engineer for asic design and verification",
        "ai researcher with publication in top tier conferences", "nlp engineer for chatbot and language modeling",
        "computer vision engineer for image recognition projects", "deep learning engineer for generative ai models",
        "robotics engineer for autonomous navigation systems", "game developer with Unity or Unreal Engine",
        "vr ar developer for immersive experience design", "cryptography engineer for secure communication",
        "network architect for enterprise wide infrastructure", "it consultant for digital transformation projects",
        "business analyst for requirement gathering and analysis", "erp consultant for sap or oracle implementation",
        "crm consultant for salesforce or dynamics 365", "data engineer for building robust data pipelines",
        "big data engineer with spark and hadoop knowledge", "bi developer for creating interactive dashboards",
        "clinical research associate for pharmaceutical trials", "medical officer for multi specialty hospital",
        "radiology technician for advanced imaging center", "pharmacist for retail or hospital pharmacy",
        "physiotherapist for rehabilitation clinic", "dentist for private practice or dental chain",
        "veterinarian for small or large animal care", "chemist for research and development in lab",
        "biologist for environmental conservation project", "physicist for material science research",
        "geologist for mineral exploration company", "meteorologist for weather forecasting agency",
        "astronomer for observatory or research institute", "statistician for data analysis in government",
        "economist for policy research and analysis", "sociologist for social impact assessment",
        "psychologist for clinical or counseling practice", "anthropologist for cultural research projects",
        "political analyst for strategic consulting firm", "journalist for digital or print media house",
        "editor for magazine or online publication", "copywriter for advertising or creative agency",
        "public relations officer for corporate communication", "social media strategist for brand building",
        "digital marketing manager for seo and sem", "brand manager for fmcg or consumer goods",
        "product marketing manager for b2b saas", "sales director for regional market expansion",
        "account manager for maintaining client relationships", "customer success manager for app retention",
        "technical support specialist for hardware or softaware", "service desk analyst for it incidents",
        "project coordinator for managing project timelines", "program manager for cross functional initiatives",
        "agile coach for mentoring development teams", "delivery manager for ensuring project quality",
        "chief technology officer for technical vision", "chief operating officer for business operations",
        "chief financial officer for financial strategy", "chief executive officer for overall leadership",
        "legal counsel for corporate law and compliance", "paralegal for assisting in legal research",
        "compliance officer for regulatory adherence", "internal auditor for risk assessment and control",
        "financial controller for budget management", "treasury manager for cash flow optimization",
        "investment banker for mergers and acquisitions", "portfolio manager for asset allocation",
        "equity researcher for stock market analysis", "risk manager for identifying financial risks",
        "actuary for insurance risk modeling", "tax consultant for corporate or personal tax",
        "hr manager for talent management and relations", "training and development manager for learning",
        "compensation and benefits manager for payroll", "employee engagement specialist for culture",
        "facilities manager for building and workspace", "office manager for day to day operations",
        "executive assistant for senior management support", "administrative assistant for department tasks",
        "customer service representative for call center", "call center supervisor for team performance",
        "retail store manager for sales and inventory", "visual merchandiser for store layout design",
        "logistics manager for supply chain coordination", "supply chain analyst for process optimization",
        "procurement manager for vendor selection and buying", "quality manager for manufacturing standards",
        "safety officer for construction or plant safety", "environmental engineer for sustainability",
        "architect for residential and commercial design", "interior designer for office or home space",
        "urban planner for city development projects", "landscape architect for outdoor space design",
        "civil site engineer for project execution", "structural engineer for building stability",
        "electrical site engineer for power distribution", "mechanical site engineer for hvac and plumbing",
        "hotel manager for hospitality and guest service", "event manager for corporate or social events",
        "travel agent for tour planning and booking", "airline pilot for commercial or cargo flights",
        "flight attendant for in flight service and safety", "ground staff for airport operations",
        "train driver for passenger or freight rail", "bus driver for public or private transport",
        "delivery partner for courier or food delivery", "real estate agent for property sales and rent",
        "property manager for building maintenance", "appraiser for real estate valuation",
        "mortgage broker for assisting in home loans", "insurance agent for policy sales and service",
        "fitness trainer for gym or personal coaching", "yoga instructor for wellness and meditation",
        "nutritionist for diet planning and health", "makeup artist for bridal or fashion shoot",
        "photographer for events or commercial projects", "videographer for film or digital content",
        "animator for 2d or 3d graphics and video", "motion designer for visual effects and ui",
        "video editor for post production of content", "sound engineer for recording and mixing",
        "lighting technician for stage or studio", "performer for theater or live events",
        "artist for painting or digital illustrations", "sculptor for creative or commercial work",
        "fashion designer for apparel and accessories", "textile designer for print and fabric",
        "merchandise planner for retail buying", "e-commerce manager for online store growth",
        "web analyst for tracking website performance", "growth hacker for rapid user acquisition",
        "community manager for social media groups", "affiliate manager for partner programs",
        "email marketing specialist for campaign reach", "content strategist for planning of assets",
        "copy editor for refining written material", "proofreader for fixing errors in text",
        "translator for multi language document conversion", "interpeter for real time verbal translation",
        "librarian for managing book collections", "curator for museum or art gallery",
        "archivist for preserving historical records", "research scientist for academic or lab work",
        "teaching assistant for supporting educators", "professor for higher education instruction",
        "dean for managing academic departments", "tutor for personalized student learning",
        "coach for sports or professional development", "mentor for providing career guidance",
        "volunteer for non profit or community service", "activist for social or environmental causes",
        "pastor or religious leader for community", "non profit director for managing charity work",
        "fundraiser for raising money for causes", "grant writer for securing project funding",
        "social worker for community support systems", "public health officer for community wellness",
        "policy maker for government or ngo roles", "diplomat for international relations and trade",
        "military officer for defense and security", "police officer for law enforcement duties",
        "firefighter for emergency response and safety", "paramedic for first aid and medical care",
        "postal worker for mail and package delivery", "sanitation worker for public health services",
        "utility worker for electricity water or gas", "technician for repairing home appliances",
        "carpenter for furniture or building work", "plumber for water and pipe systems",
        "electrician for wiring and electrical tasks", "mason for brick and stone construction",
        "painter for residential or industrial jobs", "roofer for fixing and installing roofs",
        "welder for metal fabrication and repair", "mechanic for vehicle or machine maintenance",
        "machinist for operating precise tools", "assembler for product manufacturing lines",
        "factory worker for mass production tasks", "manual laborer for physical work on sites",
        "landscaper for maintaining gardens and lawns", "forester for forest management and care",
        "farmer for crop production and animal husbandry", "rancher for livestock and cattle care",
        "fisherman for commercial or private fishing", "miner for extracting minerals and ores",
        "oil rig worker for offshore or onshore drills", "deckhand for working on ships or boats",
        "captain for leading maritime vessels", "flight dispatcher for planning aircraft routes",
        "air traffic controller for managing airspace", "baggage handler for airport logistics",
        "gate agent for managing passenger boarding", "reservation agent for booking services",
        "concierge for assisting hotel guests", "bellhop for handling guest luggage",
        "housekeeper for cleaning rooms and areas", "laundry attendant for washing and ironing",
        "dishwasher for cleaning kitchen utensils", "prep cook for assisting in kitchen tasks",
        "barista for making and serving coffee", "bartender for mixing and serving drinks",
        "host for greeting guests in restaurants", "busser for clearing and setting tables",
        "cashier for handling payments and billing", "stocker for replenishing store shelves",
        "bagger for packing customer purchases", "clerk for managing data and files",
        "proofreader for checking spelling and grammar", "indexer for creating search catalogs",
        "transcriber for converting audio to text", "captioner for adding text to videos",
        "notary for legally witnessing signatures", "courier for fast delivery of documents",
        "messengar for local pickup and drop off", "usher for guiding people in events",
        "docent for providing tours in museums", "lifeguard for ensuring safety in pools",
        "caddie for assisting golfers on course", "choreographer for designing dance routines"
    ],
    "label": ["Fake"] * 325 + ["Real"] * 327 
}




df = pd.DataFrame(data)
df["text"] = df["text"].apply(clean_text)

X = df["text"]
y = df["label"]

vectorizer = TfidfVectorizer(stop_words='english')
X_vec = vectorizer.fit_transform(X)

model = LogisticRegression()
model.fit(X_vec, y)

pickle.dump(model, open("model.pkl","wb"))
pickle.dump(vectorizer, open("vectorizer.pkl","wb"))

print("Model trained successfully")
